<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_confirmDeleteCart</name>
   <tag></tag>
   <elementGuidId>1d2d0d1d-3673-4374-98f4-f7baa9f6f1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[id=&quot;remove-all-confirmation-modal&quot;]>div>div>div[class=&quot;modal-actions&quot;]>button[class=&quot;primary&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
