<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_useShipToCheckbox</name>
   <tag></tag>
   <elementGuidId>5db72e7f-38db-43eb-a7ef-80bcebcd9932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;shipToAsDelivery&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkoutPaymentmethod-po</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pmnt&quot;)/div[@class=&quot;payment-cc-po-wrapper x:row&quot;]/div[@class=&quot;payment-methods x:col-12&quot;]/div[@class=&quot;payment-method-options x:row&quot;]/div[@class=&quot;payment-method-option x:ml-xxl&quot;]/div[@class=&quot;xng-field xng-radio  ng-not-empty&quot;]/div[@class=&quot;input&quot;]/label[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;shipToAsDelivery&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
