<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_productContainer</name>
   <tag></tag>
   <elementGuidId>2116cf32-592c-4a1d-9d76-ed84cc7c9409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul[id=&quot;tst_productList_nonTable&quot;]>li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
