<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_CVV</name>
   <tag></tag>
   <elementGuidId>31cb97a4-8122-41e0-8b41-a3575445aada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_ppTokenExSecurityCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_ppTokenExSecurityCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=4MXpnHhLxuH9qFDlkB5pUoi7IDSm%2Fv+caWDQPTiRkZ8%3D&amp;Origin=http%3A%2F%2Fwernerelectric-qa.xngage.net&amp;TokenExID=2183715521317164&amp;Timestamp=20200902154415&amp;Container=ppTokenExSecurityCode&amp;Mode=CVV&amp;PCI=true&amp;Token=5179989769601111&amp;CvvOnly=true&amp;CvvContainer=undefined&amp;CVV=true&amp;TokenScheme=TOKENfour</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_ppTokenExSecurityCode</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_ppTokenExSecurityCode</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_ppTokenExSecurityCode&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_ppTokenExSecurityCode']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ppTokenExSecurityCode']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
