<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shippingInstructionsField</name>
   <tag></tag>
   <elementGuidId>2db951c5-6033-4934-aa6c-eac15c5477f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nwrap&quot;]/div[1]/div[2]/div[2]/div/div/div/div/div/section[2]/div[1]/div[1]/div[2]/div/div[2]/div[2]/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.ng-untouched.ng-valid.ng-valid-max-length.ng-valid-custom-validate-injector.ng-not-empty.ng-dirty.ng-valid-parse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.cart.notes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xng-validate</name>
      <type>Main</type>
      <value>{maxLength: 300}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-valid-max-length ng-valid-custom-validate-injector ng-not-empty ng-dirty ng-valid-parse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nwrap&quot;)/div[@class=&quot;off-canvas panelwrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;cms-rearrangeable&quot;]/div[@class=&quot;cms-currentPage&quot;]/div[@class=&quot;main-row block-container checkout-review-pay&quot;]/div[@class=&quot;page-content-wrapper&quot;]/div[@class=&quot;shipping-mode&quot;]/div[@class=&quot;werner-checkout-widget&quot;]/section[@class=&quot;checkout__container&quot;]/div[@class=&quot;checkout__content&quot;]/div[@class=&quot;checkout__step shipping-step&quot;]/div[@class=&quot;checkout-step__content shipping-wrapper x:row&quot;]/div[@class=&quot;x:col-12 x:row ship-method&quot;]/div[@class=&quot;x:col-6 md:col-12  x:pl-xxl md:pl-none&quot;]/div[@class=&quot;shipping-intructions&quot;]/div[@class=&quot;xng-field w-xng-field  ng-not-empty&quot;]/div[@class=&quot;input&quot;]/textarea[@class=&quot;ng-untouched ng-valid ng-valid-max-length ng-valid-custom-validate-injector ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nwrap']/div/div[2]/div[2]/div/div/div/div/div/section[2]/div/div/div[2]/div/div[2]/div[2]/div/div/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
