<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_addItemToList</name>
   <tag></tag>
   <elementGuidId>cd530c65-df81-4ef9-bcb8-4a91687a95f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[ng-click^=&quot;vm.addProductToList&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
